server:
  port: 9092

spring:
  application:
    name: springBoot-springAI
  ai:
    dashscope:
      api-key: sk-d7054f6e531c41ceb5b276b3ce24388c
      base-url: https://api.siliconflow.cn

  data:
    redis:
      host: 127.0.0.1 # 39.96.202.75
      port: 6379
      database: 1
      password: 123456

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/person_blog?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456

files:
  upload:
    path: /opt/deploy/person_blog/files

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: myself.springboot.entity

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

fileUrl:
  upload:
    address: "http://39.96.202.75:9092"

cors:
  allowed-origins:
    http://39.96.202.75:8082
